const keyboardMapArray = [
    { id: "1", keyNotation: "Q", octave: "4", basenote: "C", className: "white" },
    { id: "2", keyNotation: "2", octave: "4", basenote: "C#", className: "black" },
    { id: "3", keyNotation: "W", octave: "4", basenote: "D", className: "white offset" },
    { id: "4", keyNotation: "3", octave: "4", basenote: "D#", className: "black" },
    { id: "5", keyNotation: "E", octave: "4", basenote: "E", className: "white offset" },
    { id: "6", keyNotation: "R", octave: "4", basenote: "F", className: "white" },
    { id: "7", keyNotation: "5", octave: "4", basenote: "F#", className: "black" },
    { id: "8", keyNotation: "T", octave: "4", basenote: "G", className: "white offset" },
    { id: "9", keyNotation: "6", octave: "4", basenote: "G#", className: "black" },
    { id: "10", keyNotation: "Y", octave: "4", basenote: "A", className: "white offset" },
    { id: "11", keyNotation: "7", octave: "4", basenote: "A#", className: "black" },
    { id: "12", keyNotation: "U", octave: "4", basenote: "B", className: "white offset" },
    { id: "13", keyNotation: "I", octave: "5", basenote: "C", className: "white" },
    { id: "14", keyNotation: "9", octave: "5", basenote: "C#", className: "black" },
    { id: "15", keyNotation: "O", octave: "5", basenote: "D", className: "white offset" },
    { id: "16", keyNotation: "0", octave: "5", basenote: "D#", className: "black" },
    { id: "17", keyNotation: "P", octave: "5", basenote: "E", className: "white offset" },
    { id: "18", keyNotation: "Z", octave: "5", basenote: "F", className: "white" },
    { id: "19", keyNotation: "S", octave: "5", basenote: "F#", className: "black" },
    { id: "20", keyNotation: "X", octave: "5", basenote: "G", className: "white offset" },
    { id: "21", keyNotation: "D", octave: "5", basenote: "G#", className: "black" },
    { id: "22", keyNotation: "C", octave: "5", basenote: "A", className: "white offset" },
    { id: "23", keyNotation: "F", octave: "5", basenote: "A#", className: "black" },
    { id: "24", keyNotation: "V", octave: "2", basenote: "B", className: "white offset" },
    { id: "25", keyNotation: "B", octave: "6", basenote: "C", className: "white" },
    { id: "26", keyNotation: "H", octave: "6", basenote: "C#", className: "black" },
    { id: "27", keyNotation: "N", octave: "6", basenote: "D", className: "white offset" },
    { id: "28", keyNotation: "J", octave: "6", basenote: "D#", className: "black" },
    { id: "29", keyNotation: "M", octave: "6", basenote: "E", className: "white offset" },
    { id: "30", keyNotation: ",", octave: "6", basenote: "F", className: "white" },
    { id: "31", keyNotation: "L", octave: "6", basenote: "F#", className: "black" },
    { id: "32", keyNotation: ".", octave: "6", basenote: "G", className: "white offset" },
    { id: "33", keyNotation: ";", octave: "6", basenote: "G#", className: "black" },
    { id: "34", keyNotation: "/", octave: "6", basenote: "A", className: "white offset" },
    { id: "35", keyNotation: "'", octave: "6", basenote: "A#", className: "black" },
    { id: "36", keyNotation: "Shift", octave: "6", basenote: "B", className: "white offset" },
  ]
  

  
  export default keyboardMapArray;